services:
    # web:
    #     image: nginx:stable-alpine
    #     volumes:
    #     - ./web:/www/data
    #     - ./storage:/www/data/files
    #     ports:
    #     - "8080:80"
    leroy:
        image: michaelbosworth/project-leroy:latest
        privileged: true
        volumes:
        - ./all_models:/app/all_models